name = input('input your name: ')
age = int(input('input your age in whole years: '))
weight = float(input('input your weight accurate to 0.1 kg: '))
# print('Hello, %s of %d years old and %.1f kg weight!' % (name, age, weight))
# print('Hello, {} of {} years old and {:.1f} kg weight!'.format(name, age, weight))
# print('Hello, {:s} of {:d} years old and {:.1f} kg weight!'.format(name, age, weight))
# print(f'Hello, {name} of {age} years old and {weight:.1f} kg weight!')
print(f'Hello, {name:s} of {age:d} years old and {weight:.1f} kg weight!')
